- backend/protocol/api/api_router.py
- web/src/components/auth/SignedOut.tsx
- web/src/components/sidebar/EditableFolderName.tsx
- web/src/components/sidebar/EditableViewTitle.tsx
- web/src/components/sidebar/FolderCell.tsx
- web/src/components/sidebar/FolderMenuButton.tsx
- web/src/components/sidebar/ViewCell.tsx
- web/src/components/sidebar/ViewsSection.tsx
- web/src/store/views.ts
Management for Views + Folders:
- New folder creation
- Folder renaming
- View renaming
- Drag & Drop for views between folders
> View and Folder Management

- .github/workflows/.web-quality.yml
- CLAUDE.md
- docker-compose.yml
- package-lock.json
- web.Dockerfile
- web/jest.config.js
- web/jest.setup.js
- web/package.json
- web/src/app/experiments/[id]/__tests__/utils.test.ts
- web/src/components/__tests__/SqlKeywordExtension.test.ts
- web/src/components/universal-charts/__tests__/utils.test.ts
- web/src/components/utils/__tests__/stringMatchingUtils.test.ts
- web/src/components/utils/__tests__/utils.test.ts
- web/src/components/utils/stringMatchingUtils.ts
- web/src/lib/__tests__/queryString.test.ts
- web/src/utils/__tests__/queries.test.ts
- web/src/utils/queries.ts
https://github.com/anotherai-dev/anotherai/issues/44
- Pure functions and business logic calculations
- Data transformations and utilities
- String matching algorithms
- Chart utilities and query building
- Experiment business logic
@guillaq 
For code review and QA in this case
> JEST to frontend added + Tests for Untils and Logic

- CLAUDE.md
- CONTRIBUTING.md
- README.md
fix https://github.com/anotherai-dev/anotherai/issues/89
> Update claude readme to include build docker images

- backend/protocol/api/_api_models.py
- backend/protocol/api/_api_models_test.py
Fix an issue where importing runs would be rejected because the tool call result error was omitted
> Tool call result deser

- web/src/components/CommandPalette.tsx
- web/src/components/sidebar/ViewMenuButton.tsx
https://github.com/anotherai-dev/anotherai/pull/120
> [FIX] Tapping on a view from this search command bar needs to update the URL to views instead of view to fix

- backend/protocol/api/_services/playground_service.py
- backend/tests/components/playground_test.py
ref https://github.com/anotherai-dev/anotherai/issues/131
> fix: handle empty messages in playground

- web/src/app/layout.tsx
https://linear.app/anotherai-dev/issue/AAI-61/infinite-loading-state-in-detail-view-after-logging-out
> {AAI-61] Infinite loading state in detail view after logging out

- docs/content/docs/deployments/index.mdx
- docs/content/docs/deployments/step-by-step-guide.mdx
- docs/content/docs/examples/use-cases.mdx
- docs/content/docs/foundations.mdx
- docs/content/docs/inference/caching.mdx
- docs/content/docs/migrate-from-workflowai.mdx
- docs/content/docs/partials/openai-go-code.mdx
- add go code samples to partial file
- revert passing the agent_id by metadata
> Add go code samples

- web/src/components/sidebar/NavigationSidebar.tsx
https://linear.app/anotherai-dev/issue/AAI-74/tab-order-change
> [AAI-74] Tab order change

- backend/core/domain/exceptions.py
- backend/core/storage/clickhouse/_utils_test.py
- backend/core/storage/clickhouse/clickhouse_client.py
- backend/core/storage/clickhouse/clickhouse_client_test.py
- backend/core/utils/strings.py
- backend/core/utils/strings_test.py
- backend/protocol/api/_mcp_utils.py
- backend/tests/components/completions_test.py
Prioritized because it seemed that some errors from MCP were not showing up in sentry when needed
> Better handle clickhouse errors

- web/src/app/metrics/page.tsx
- web/src/components/universal-charts/CompletionsGraph.tsx
- web/src/components/universal-charts/UniversalPieChart.tsx
- web/src/components/universal-charts/utils.ts
https://github.com/anotherai-dev/anotherai/issues/220
> [GitHub-220] Add Units to Metrics Page

- web/src/app/experiments/[id]/sections/matching/HeaderMatchingRow.tsx
- web/src/app/experiments/[id]/sections/matching/MatchingJSONValue.tsx
- web/src/app/experiments/[id]/sections/matching/MatchingRow.tsx
- web/src/components/completion-modal/MetadataView.tsx
- web/src/components/utils/utils.ts
- web/src/components/version-details/VersionDetailsRow.tsx
- web/src/components/version-details/VersionDetailsView.tsx
https://github.com/anotherai-dev/anotherai/issues/224
> [GitHub-224] Format input_varibles_schema in a better way

- web/src/app/folders/[id]/page.tsx
- web/src/components/sidebar/EditableFolderName.tsx
- web/src/components/sidebar/FolderCell.tsx
https://github.com/anotherai-dev/anotherai/issues/230
> [GitHub-230] Pages for View Folders (Dashboards!)

- web/src/app/experiments/[id]/sections/Results/MatrixSection.tsx
- web/src/app/experiments/[id]/sections/Results/version/VersionHeader.tsx
- web/src/app/globals.css
https://github.com/anotherai-dev/anotherai/issues/255
> [GitHub-255] FireFox Layout Issues for Experiment Page

- backend/protocol/api/_api_models.py
- backend/protocol/api/_mcp.py
- backend/protocol/api/_services/view_service.py
ref https://github.com/anotherai-dev/anotherai/issues/171
> Add notion of inputs and limits to create or update view

- web/src/app/experiments/[id]/__tests__/utils.test.ts
- web/src/components/utils/__tests__/utils.test.ts
- web/src/components/utils/stringMatchingUtils.ts
- web/src/lib/__tests__/queryString.test.ts
https://github.com/anotherai-dev/anotherai/issues/270
> [GitHub-270] Experiment Page: Diffs are not shown

- web/src/app/completions/page.tsx
https://github.com/anotherai-dev/anotherai/issues/293
> [GitHub-293] Completions Page Description Update

- web/src/components/payment-modal/EnableAutoRechargeContent.tsx
https://github.com/anotherai-dev/anotherai/issues/398
> [GitHub-398] Auto recharge UX improvements fixes

- web/src/app/experiments/[id]/sections/Results/version/DraggableColumnWrapper.tsx
https://github.com/anotherai-dev/anotherai/issues/384
> [GitHub-384] Coping of the Prompt Issues on the Experiment Page

- backend/core/domain/models/_mistral.py
- backend/core/domain/models/_xai.py
- backend/core/domain/models/model_data.py
- backend/core/domain/models/model_data_mapping.py
Closes https://github.com/anotherai-dev/anotherai/issues/367
> Use speed index from artificial analysis

- backend/core/storage/psql/psql_view_storage.py
- backend/core/storage/psql/psql_view_storage_test.py
- backend/tests/components/mcp/create_view_test.py
Closes https://github.com/anotherai-dev/anotherai/issues/310
> Fix updating view resets folder

- web/src/app/experiments/[id]/sections/matching/MatchingBaseValue.tsx
- web/src/app/experiments/[id]/sections/matching/MatchingJSONValue.tsx
- web/src/app/experiments/[id]/sections/matching/MatchingToolValue.tsx
- web/src/components/HoverPopover.tsx
- web/src/components/MetricItem.tsx
https://github.com/anotherai-dev/anotherai/issues/386
> [GitHub-386] Safari Percentiles Popover Layout Issues

- .gitignore
- Makefile
- backend/tests/components/server_json_test.py
- pyproject.toml
- server.json
closes https://github.com/anotherai-dev/anotherai/issues/188
> Publish MCP server on registry

- web/src/components/messages/MessageContentView.tsx
- web/src/components/messages/UniversalFileViewer.tsx
https://github.com/anotherai-dev/anotherai/issues/431
> [GitHub-431] Show types for Input Variables in Messages when they are in Contents of a Message

- web/src/components/completion-modal/MetadataView.tsx
- web/src/hooks/useCopy.ts
https://github.com/anotherai-dev/anotherai/issues?q=is%3Aissue%20state%3Aopen%20assignee%3Ajacekzimonski
> [GitHub-395] Make metadata values copiable
